version: '3.8'

services:
  backend:
    build: TweetTrack
    container_name: tweet-track-backend
    ports:
      - "8000:8000"
    volumes:
      - ./TweetTrack/api:/app/api
    environment:
      - PYTHONPATH=/app/src
      - DATABASE_URL=postgresql://postgres:tweetTrack@postgres:5432/tweettrack_db
    depends_on:
      postgres:
        condition: service_healthy 

  postgres:
    image: postgres:latest
    container_name: tweet-track-db
    restart: always
    environment:
      POSTGRES_DB: tweettrack_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tweetTrack
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  tflite-inference:
    build: AiInference
    container_name: tflite-inference
    ports:
      - "8501:8501"
    environment:
      - MODEL_PATH=/app/model.tflite

volumes:
  postgres:
