services:
  backend:
    build: TweetTrack
    container_name: tweet-track-backend
    ports:
      - "8000:8000"
    volumes:
      - ./TweetTrack/api:/app/api
      - ./TweetTrack/src:/app/src
      - ./TweetTrack/start.sh:/app/start.sh
    environment:
      - PYTHONPATH=/app/src
      - DATABASE_URL=postgresql://postgres:tweetTrack@postgres:5432/tweettrack_db
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    container_name: tweet-track-db
    restart: always
    environment:
      POSTGRES_DB: tweettrack_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tweetTrack
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  model-inference:
    build: AiInference
    container_name: model-inference
    ports:
      - "9000:9000"
    environment:
      - MODEL_PATH=/app/model.saved

volumes:
  postgres:
